// <auto-generated />
using DnDBeyond.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDBeyond.Backend.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260112190524_initialDb")]
    partial class initialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DnDBeyond.Shared.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HitPoints = 25,
                            Level = 5,
                            Name = "Briv"
                        },
                        new
                        {
                            Id = 2,
                            HitPoints = 18,
                            Level = 3,
                            Name = "Elara"
                        });
                });

            modelBuilder.Entity("DnDBeyond.Shared.Entities.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ClassLevel")
                        .HasColumnType("int");

                    b.Property<int>("HitDiceValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterId = 1,
                            ClassLevel = 5,
                            HitDiceValue = 10,
                            Name = "Fighter"
                        },
                        new
                        {
                            Id = 2,
                            CharacterId = 2,
                            ClassLevel = 3,
                            HitDiceValue = 6,
                            Name = "Wizard"
                        });
                });

            modelBuilder.Entity("DnDBeyond.Shared.Entities.Defense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("DefenseType")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Defenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterId = 1,
                            DefenseType = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 2,
                            CharacterId = 1,
                            DefenseType = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            CharacterId = 2,
                            DefenseType = 2,
                            Type = 8
                        },
                        new
                        {
                            Id = 4,
                            CharacterId = 2,
                            DefenseType = 0,
                            Type = 4
                        });
                });

            modelBuilder.Entity("DnDBeyond.Shared.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterId = 1,
                            Name = "Ioun Stone of Fortitude"
                        },
                        new
                        {
                            Id = 2,
                            CharacterId = 1,
                            Name = "Longsword +1"
                        },
                        new
                        {
                            Id = 3,
                            CharacterId = 2,
                            Name = "Staff of Fire"
                        });
                });

            modelBuilder.Entity("DnDBeyond.Shared.Entities.ItemModifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedObject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AffectedValue")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("ItemModifiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffectedObject = "stats",
                            AffectedValue = 2,
                            ItemId = 1,
                            Value = 2
                        },
                        new
                        {
                            Id = 2,
                            AffectedObject = "attack",
                            AffectedValue = 0,
                            ItemId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 3,
                            AffectedObject = "spellDamage",
                            AffectedValue = 3,
                            ItemId = 3,
                            Value = 2
                        });
                });

            modelBuilder.Entity("DnDBeyond.Shared.Entities.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterId = 1,
                            Charisma = 8,
                            Constitution = 14,
                            Dexterity = 12,
                            Intelligence = 13,
                            Strength = 15,
                            Wisdom = 10
                        },
                        new
                        {
                            Id = 2,
                            CharacterId = 2,
                            Charisma = 10,
                            Constitution = 12,
                            Dexterity = 14,
                            Intelligence = 16,
                            Strength = 8,
                            Wisdom = 13
                        });
                });

            modelBuilder.Entity("DnDBeyond.Shared.Entities.CharacterClass", b =>
                {
                    b.HasOne("DnDBeyond.Shared.Entities.Character", "Character")
                        .WithMany("Classes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DnDBeyond.Shared.Entities.Defense", b =>
                {
                    b.HasOne("DnDBeyond.Shared.Entities.Character", "Character")
                        .WithMany("Defenses")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DnDBeyond.Shared.Entities.Item", b =>
                {
                    b.HasOne("DnDBeyond.Shared.Entities.Character", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DnDBeyond.Shared.Entities.ItemModifier", b =>
                {
                    b.HasOne("DnDBeyond.Shared.Entities.Item", "Item")
                        .WithOne("Modifier")
                        .HasForeignKey("DnDBeyond.Shared.Entities.ItemModifier", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DnDBeyond.Shared.Entities.Stats", b =>
                {
                    b.HasOne("DnDBeyond.Shared.Entities.Character", "Character")
                        .WithOne("Stats")
                        .HasForeignKey("DnDBeyond.Shared.Entities.Stats", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DnDBeyond.Shared.Entities.Character", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Defenses");

                    b.Navigation("Items");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("DnDBeyond.Shared.Entities.Item", b =>
                {
                    b.Navigation("Modifier");
                });
#pragma warning restore 612, 618
        }
    }
}
